import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/navbar";
import Footer from "./components/footer";
import Bottom from "./components/bottom";


 


const inter = Inter({ subsets: ["latin"] });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="max-w-[1920px]">
      
      <body className={inter.className} >
        <Header />
        {children}
        <Footer />
        <Bottom />
        </body>
    </html>
  );
}
 